spring:
  datasource:
    url: jdbc:mysql://117.17.142.207:3306/spring_portal?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cs616
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

com:
  skuniv:
    cs:
      geonyeong:
        crypt:
          key: 123456789789456123456
        jwt:
          secretKey : ThisIsGeonyeongKimWithLyangHwaSpringPortalProjectJwtSecretKey